/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import setoran.DatabaseUser;
import setoran.Koneksi;
import setoran.Motor;

/**
 *
 * @author YOGA
 */
public class DialogTambahMotor extends javax.swing.JDialog {
    String inputPlatNomor;
    String inputBrand;
    String inputTipe;
    int inputTahun;
    String inputTransmisi;
    int inputSilinder;
    int inputHargaHari;
    
    PanelMotorSaya panelMotor = null;

    public DialogTambahMotor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
    public DialogTambahMotor(java.awt.Frame parent, boolean modal, PanelMotorSaya panelMotor) {
        super(parent, modal);
        initComponents();

        this.panelMotor = panelMotor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        platNomorField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tahunSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        transmisiBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        silinderSpinner = new javax.swing.JSpinner();
        simpanBtn = new javax.swing.JButton();
        hargaHariSpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 350));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambah Motor");

        jLabel2.setText("Plat Nomor");

        jLabel3.setText("Brand");

        jLabel4.setText("Tipe");

        jLabel5.setText("Tahun");

        jLabel6.setText("Transmisi");

        transmisiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Matic" }));

        jLabel7.setText("Silinder");

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga / Hari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(simpanBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(platNomorField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(brandField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipeField)
                            .addComponent(tahunSpinner)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(transmisiBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(silinderSpinner)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargaHariSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(platNomorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tahunSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(transmisiBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(silinderSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hargaHariSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        inputPlatNomor = platNomorField.getText();
        inputBrand = brandField.getText();
        inputTipe = tipeField.getText();
        inputTahun = (int) tahunSpinner.getValue();
        inputTransmisi = transmisiBox.getSelectedItem().toString();
        inputSilinder = (int) silinderSpinner.getValue();
        inputHargaHari = (int) hargaHariSpinner.getValue();
            
        try {
            
            int platNomorLen = inputPlatNomor.length();
            if (platNomorLen < 5) {
                JOptionPane.showMessageDialog(this, "Plat nomor terlalu pendek", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (platNomorLen > 10) {
                JOptionPane.showMessageDialog(this, "Plat nomor terlalu panjang", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int brandLen = inputBrand.length();
            if (brandLen < 3) {
                JOptionPane.showMessageDialog(this, "Brand terlalu pendek", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (brandLen > 20) {
                JOptionPane.showMessageDialog(this, "Brand terlalu panjang", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int tipeLen = inputTipe.length();
            if (tipeLen < 3) {
                JOptionPane.showMessageDialog(this, "Nama tipe terlalu pendek", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (tipeLen > 20) {
                JOptionPane.showMessageDialog(this, "Nama tipe terlalu panjang", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (inputSilinder < 100) {
                JOptionPane.showMessageDialog(this, "Silinder terlalu kecil", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (inputSilinder > 250) {
                JOptionPane.showMessageDialog(this, "Silinder terlalu besar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (inputTahun < 2010) {
                JOptionPane.showMessageDialog(this, "Motor harus dalam rentang tahun 2010 dan sekarang", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
          
            if (inputTahun > 2024) {
                JOptionPane.showMessageDialog(this, "Motor harus dalam rentang tahun 2010 dan sekarang", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }         
            
            if (inputHargaHari < 30000) {
                JOptionPane.showMessageDialog(this, "Harga motor terlalu murah", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
          
            if (inputHargaHari > 500000) {
                JOptionPane.showMessageDialog(this, "Harga motor terlalu mahal", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }         
            
            
            String sql = String.format("SELECT * FROM motor WHERE plat_nomor='%s' and deleted = 'false'", inputPlatNomor);
            List<Motor> existing = Koneksi.query(sql, Motor.class);
            if (existing == null) {
                JOptionPane.showMessageDialog(this, "Motor sudah ter registrasi", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            sql = "INSERT INTO `motor` (`id_motor`, `plat_nomor`, `brand`, `tipe`, `tahun`, `transmisi`, `status_motor`, `silinder`, `harga_harian`, `id_pemilik`) VALUES (NULL, '" + inputPlatNomor + "', '" + inputBrand + "', '"+ inputTipe +"', " + inputTahun + ", '" + inputTransmisi + "', 'Tersedia', " + inputSilinder + ", " + inputHargaHari + ", " + DatabaseUser.currentUser.getIdUser() + ")";
            Koneksi.update(sql);
            JOptionPane.showMessageDialog(this, "Berhasil Menambahkan Motor");
            ((HomePage)this.getParent()).refresh();
            this.dispose();
            
            if (panelMotor != null)
                panelMotor.getData();
        } catch (SQLException ex) {
            Logger.getLogger(DialogTambahMotor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogTambahMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogTambahMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogTambahMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogTambahMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogTambahMotor dialog = new DialogTambahMotor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandField;
    private javax.swing.JSpinner hargaHariSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField platNomorField;
    private javax.swing.JSpinner silinderSpinner;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JSpinner tahunSpinner;
    private javax.swing.JTextField tipeField;
    private javax.swing.JComboBox<String> transmisiBox;
    // End of variables declaration//GEN-END:variables


//Cara lama menghitung harga
//Diganti untuk PPL
    
//    private int hitungHarga(int silinder, String transmisi) {
//        if (transmisi.equals("Matic")) {
//            if (silinder < 150) {
//                return 45000;
//            } else if (silinder >= 150) {
//                return 55000;
//            }
//        } else {
//            if (silinder < 150) {
//                return 40000;
//            } else if (silinder >= 150) {
//                return 60000;
//            }
//        }
//        return 0;
//    }
}
