/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import setoran.*;
/**
 *
 * @author ASUS
 */
public class PanelSewa extends javax.swing.JPanel {
    
    DefaultTableModel model;
    ArrayList<Motor> listMotor = new ArrayList<>();;
    Motor selectedMotor;
    Koneksi kn;
    
    public PanelSewa() {
        initComponents();
        Koneksi.getConnection();
        model = (DefaultTableModel) motorTable.getModel();
        motorTable.getColumnModel().getColumn(0).setPreferredWidth(25);
        getData();
//        motorTable.removeColumn(motorTable.getColumnModel().getColumn(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        motorTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BrandDropdown = new javax.swing.JComboBox<>();
        transmisiFilterLabel = new javax.swing.JLabel();
        transmisiDropdown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sewaBtn = new javax.swing.JButton();
        nomorPolisiLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        tipeLabel = new javax.swing.JLabel();
        transmisiLabel = new javax.swing.JLabel();
        tahunLabel = new javax.swing.JLabel();
        silinderLabel = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        motorTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        motorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Plat Nomor", "Brand", "Tipe", "Transmisi", "Tahun"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        motorTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        motorTable.setRowHeight(30);
        motorTable.getTableHeader().setResizingAllowed(false);
        motorTable.getTableHeader().setReorderingAllowed(false);
        motorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                motorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(motorTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Brand");

        BrandDropdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BrandDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Honda", "Yamaha", "Suzuki" }));
        BrandDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandDropdownActionPerformed(evt);
            }
        });

        transmisiFilterLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        transmisiFilterLabel.setText("Transmisi");

        transmisiDropdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        transmisiDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Matic", "Semi Matic", "Manual" }));
        transmisiDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmisiDropdownActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tipe");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButton2.setText("🔍");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Detail Motor");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nomor Polisi :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Brand");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tipe");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Transmisi");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tahun");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Silinder");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Harga");

        sewaBtn.setText("Sewa");
        sewaBtn.setEnabled(false);

        nomorPolisiLabel.setText("jLabel12");

        brandLabel.setText("jLabel13");

        tipeLabel.setText("jLabel14");

        transmisiLabel.setText("jLabel15");

        tahunLabel.setText("jLabel16");

        silinderLabel.setText("jLabel17");

        hargaLabel.setText("jLabel18");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BrandDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(transmisiFilterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transmisiDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(sewaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorPolisiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transmisiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tahunLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(silinderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorPolisiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transmisiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tahunLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(silinderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sewaBtn)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BrandDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(transmisiFilterLabel)
                            .addComponent(transmisiDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BrandDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandDropdownActionPerformed
        getData();
    }//GEN-LAST:event_BrandDropdownActionPerformed

    private void transmisiDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmisiDropdownActionPerformed
        getData();
    }//GEN-LAST:event_transmisiDropdownActionPerformed

    private void motorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motorTableMouseClicked
//        ListSelectionModel selectedModel = motorTable.getSelectionModel();
//        if (!selectedModel.equals(null)) {
//            String nomorPlat = selectedModel.get
//        }
//        int selectedRowIdx = motorTable.getSelectedRow();
//        if (selectedRowIdx != -1) {
//            String nomorPlat = motorTable.getModel().getValueAt(selectedRowIdx, 1).toString();
//            System.out.println(nomorPlat);
//            
//            
//        }

        selectedMotor = listMotor.get(motorTable.getSelectedRow());
        if (selectedMotor != null) {
            System.out.println(selectedMotor.getTipe());
            nomorPolisiLabel.setText(selectedMotor.getPlatNomor());
            brandLabel.setText(selectedMotor.getBrand());
            tipeLabel.setText(selectedMotor.getTipe());
            tahunLabel.setText(selectedMotor.getTahun());
            transmisiLabel.setText(selectedMotor.getTransmisi());
            silinderLabel.setText(Integer.toString(selectedMotor.getSilinder()));
            hargaLabel.setText(Integer.toString(selectedMotor.getHargaHarian()));
            
            sewaBtn.setEnabled(true);
        } else {
            sewaBtn.setEnabled(false);
        }
    }//GEN-LAST:event_motorTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BrandDropdown;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable motorTable;
    private javax.swing.JLabel nomorPolisiLabel;
    private javax.swing.JButton sewaBtn;
    private javax.swing.JLabel silinderLabel;
    private javax.swing.JLabel tahunLabel;
    private javax.swing.JLabel tipeLabel;
    private javax.swing.JComboBox<String> transmisiDropdown;
    private javax.swing.JLabel transmisiFilterLabel;
    private javax.swing.JLabel transmisiLabel;
    // End of variables declaration//GEN-END:variables

    private void getData() {
        clearTable();
        
        try {
            String sql = "SELECT * FROM motor WHERE status_motor = 'Tersedia'";
            
            if (BrandDropdown.getSelectedIndex() != 0) {
                sql += "AND brand = '" + BrandDropdown.getSelectedItem().toString() + "'";
            }
            if (transmisiDropdown.getSelectedIndex() != 0) {
                sql += "AND transmisi = '" + transmisiDropdown.getSelectedItem().toString() + "'";
            }
            Koneksi.query(sql);
            while(Koneksi.rs.next()){
                int idMotor = Koneksi.rs.getInt("id_motor");
                String platNomor = Koneksi.rs.getString("plat_nomor");
                String brand = Koneksi.rs.getString("brand");
                String tipe = Koneksi.rs.getString("tipe");
                String tahun = Koneksi.rs.getString("tahun");
                String transmisi = Koneksi.rs.getString("transmisi");
                String statusMotor = Koneksi.rs.getString("status_motor");
                int silinder = Koneksi.rs.getInt("silinder");
                int hargaHarian = Koneksi.rs.getInt("harga_harian");
                
                listMotor.add(new Motor(idMotor, platNomor, brand, tipe, tahun, transmisi, statusMotor, silinder, hargaHarian));
            }
            
            for (int i = 0; i < listMotor.size(); i++) {
                Object[] rowData = {i + 1, listMotor.get(i).getPlatNomor(),listMotor.get(i).getBrand(), listMotor.get(i).getTipe(), listMotor.get(i).getTransmisi(), listMotor.get(i).getTahun()};
                model.addRow(rowData);
            }
        } catch (SQLException e) {
            Logger.getLogger(Koneksi.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
//    private void getData(String brand) {
//        DefaultTableModel model = (DefaultTableModel) motorTable.getModel();
//        model.setRowCount(0);
//        
//        try {
//            String sql = "SELECT * FROM motor WHERE status_motor = 'Tersedia' and brand = '" + brand + "'";
////            PreparedStatement st = conn.prepareStatement(sql);
////            ResultSet rs = st.executeQuery(sql);
//            ResultSet rs = Koneksi.query(sql);
//            
//            while(rs.next()){
//                String platNomor = rs.getString("plat_nomor");
//                String brands = rs.getString("brand");
//                String tipe = rs.getString("tipe");
//                String tahun = rs.getString("tahun");
//                
//                Object[] rowData = {platNomor, brands, tipe, tahun};
//                model.addRow(rowData);
//            }
//            
//            rs.close();
////            st.close();
//        } catch (Exception e) {
//            Logger.getLogger(Koneksi.class.getName()).log(Level.SEVERE, null, e);
//        }
//    }
    
    private void clearTable() {
        model.setRowCount(0);
        listMotor.clear();
    }
}
